server:
  port: 9999

security:
  user:
    password: user
  ignored: /,/favicon.ico,/index.html,/home.html,/dashboard.html,/js/**,/css/**,/webjars/**
  sessions: ALWAYS
  oauth2:
    sso:
      loginPath: /dashboard/login
management:
  security:
    role: HERO

logging:
  level:
    org.springframework.security: INFO
    com.netflix.discovery: 'OFF'

zuul:
  routes:
    users:
      path: /users/**
      url: http://localhost:8080/uaa/Users

---
spring:
  profiles: default
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8080/uaa/oauth/token
      userAuthorizationUri: http://localhost:8080/uaa/oauth/authorize
      clientId: dashboard
      clientSecret: dashboardsecret
    resource:
      jwt:
        keyValue: tokenkey
---
spring:
  profiles: github
security:
  oauth2:
    client:
      clientId: 89630a412fa314777dc2
      clientSecret: c7a29ec26ec7805e78b496ea67cc13e5a9b8bcf0
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user
      preferTokenInfo: false

    